### ISSUE TITLE
The Classics Show

### ISSUE THREAD

**Issue by urnbot** [URN/urn-history-project#30]
End user submitted issue from page: [/collect/show/](https://history.urn1350.net/collect/show/)
---
# 'Tell us about a show' form submission

Field | Data
----- | ----
Title | The Classics Show
Date Start |  /  / 
Date End |  /  / 
Type | After Dark
Venue | Portland Basement

## Synopsis

Played picks of classical music. With the changeover of presenter to Fred Lloyd Williams, film music was also included. The show was later known for the predominance of carols in summer, Jim Fassett's shocking Symphony of the Birds, and extremely tenuous links.

## Presenters

Presenters throughout History:

Joe Archer (Don't know when started or kicked off)
Stephen Kenny (Not sure when started, finished December 2016)
Fred Lloyd Williams (December 2016-2019)

Regular Guests:
Paul Thomé
Paul Masson
Bessie Ephgrave

## Anything Else

I do not know the start year of the show, nor the end as I am likely continuing it on a reduced scale this year.

## Submitter

Field | Data
----- | ----
Name | Frederick Lloyd Williams
Graduated | 2018

## Attempted File Generation

```
---
title: The Classics Show
show_type: ??? (After Dark)
show_type_sort: ??
period: ??
venue:
  - Portland Basement
date_start: --
date_end: --

cast:
  - role:
    name:

crew:
  - role: Director
    name:
  - role: Producer
    name:

comment: Details from Frederick Lloyd Williams (2018)
published: true
---

Played picks of classical music. With the changeover of presenter to Fred Lloyd Williams, film music was also included. The show was later known for the predominance of carols in summer, Jim Fassett's shocking Symphony of the Birds, and extremely tenuous links.
```
**
