### ISSUE TITLE
The Official Pre-Ocean show

### ISSUE THREAD

**Issue by urnbot** [URN/urn-history-project#31]
End user submitted issue from page: [/collect/show/](https://history.urn1350.net/collect/show/)
---
# 'Tell us about a show' form submission

Field | Data
----- | ----
Title | The Official Pre-Ocean show
Date Start | 01 / 09 / 2015
Date End | 01 / 08 / 2017
Type | After dark 
Venue | The old studio 

## Synopsis

Graydon this is sick!! Love the idea!

Manley

## Presenters

MATTHEW FUCKING MANLEY

## Crew

Matthew Manley - producer, presenter, don

## Anything Else

Please don’t include Malone’s tenure

## Submitter

Field | Data
----- | ----
Name | Manley 
Graduated | 2017

## Attempted File Generation

```
---
title: The Official Pre-Ocean show
show_type: ??? (After dark )
show_type_sort: ??
period: ??
venue:
  - The old studio 
date_start: 2015-09-01
date_end: 2017-08-01

cast:
  - role:
    name:

crew:
  - role: Director
    name:
  - role: Producer
    name:

comment: Details from Manley  (2017)
published: true
---

Graydon this is sick!! Love the idea!


Manley
```
**
