### ISSUE TITLE
The Drum and Bangers Show

### ISSUE THREAD

**Issue by urnbot** [URN/urn-history-project#36]
End user submitted issue from page: [/collect/show/](https://history.urn1350.net/collect/show/)
---
# 'Tell us about a show' form submission

Field | Data
----- | ----
Title | The Drum and Bangers Show
Date Start | 5 / 11 / 2016
Date End | 20 / 5 / 2017
Type | After Dark
Venue | Portland A Floor

## Synopsis

The Drum and Bangers Show a drum and bass show broadcasted every saturday night at 11pm. Not only did Jacques Hockey present and write the shows but he would also bring his own exclusive radio debut mixes. During the shows' tenure, there were guest mixes by top producers from some of the internets biggest music production websites as well as rappers who added vocals to the tunes live in the URN studio. Various guest presenters from the uni community were invited onto the show also. Interviews were with top artists were set up for the show including Ownglow (nominated for best DNB newcomer and also remaining a friend of the show) and Delta Heavy (an artist with over 100M youtube views) - both of which providing sound clips shouting out the show and URN.

## Presenters

Presenter - Jacques Hockey

## Submitter

Field | Data
----- | ----
Name | Jacques Hockey
Graduated | 2017

## Attempted File Generation

```
---
title: The Drum and Bangers Show
show_type: ??? (After Dark)
show_type_sort: ??
period: ??
venue:
  - Portland A Floor
date_start: 2016-11-5
date_end: 2017-5-20

cast:
  - role:
    name:

crew:
  - role: Director
    name:
  - role: Producer
    name:

comment: Details from Jacques Hockey (2017)
published: true
---

The Drum and Bangers Show a drum and bass show broadcasted every saturday night at 11pm. Not only did Jacques Hockey present and write the shows but he would also bring his own exclusive radio debut mixes. During the shows' tenure, there were guest mixes by top producers from some of the internets biggest music production websites as well as rappers who added vocals to the tunes live in the URN studio. Various guest presenters from the uni community were invited onto the show also. Interviews were with top artists were set up for the show including Ownglow (nominated for best DNB newcomer and also remaining a friend of the show) and Delta Heavy (an artist with over 100M youtube views) - both of which providing sound clips shouting out the show and URN.
```
**
