### ISSUE TITLE
The Identity Talk

### ISSUE THREAD

**Issue by urnbot** [URN/urn-history-project#38]
End user submitted issue from page: [/collect/show/](https://history.urn1350.net/collect/show/)
---
# 'Tell us about a show' form submission

Field | Data
----- | ----
Title | The Identity Talk
Date Start | 18 / 04 / 2016
Date End | 12 / 02 / 2018
Type | Speech
Venue | Portland A floor

## Synopsis

The Identity Talk started as an LGBTQ+ show and evolved into a wider chat discussing different ways of identifying, with the focus on various student experiences. Covering things like disabilities, race, religion, gender and sexuality, nationality, and language, just to name a few, the show tackled a new topic each week.

## Presenters

Presenters - Ibtisam Ahmed, Doni Mozaffari, Antoinette Belle, Will Edward Smith, Helix Heyer
Producers - Ibtisam Ahmed, Doni Mozaffari, Antoinette Belle, Shivani Dave

## Anything Else

Ran every Monday but did miss a couple of slots due to ill health

## Submitter

Field | Data
----- | ----
Name | Ibtisam Ahmed
Graduated | 2019

## Attempted File Generation

```
---
title: The Identity Talk
show_type: ??? (Speech)
show_type_sort: ??
period: ??
venue:
  - Portland A floor
date_start: 2016-04-18
date_end: 2018-02-12

cast:
  - role:
    name:

crew:
  - role: Director
    name:
  - role: Producer
    name:

comment: Details from Ibtisam Ahmed (2019)
published: true
---

The Identity Talk started as an LGBTQ+ show and evolved into a wider chat discussing different ways of identifying, with the focus on various student experiences. Covering things like disabilities, race, religion, gender and sexuality, nationality, and language, just to name a few, the show tackled a new topic each week.
```
**
