### ISSUE TITLE
The Science Show

### ISSUE THREAD

**Issue by urnbot** [URN/urn-history-project#58]
End user submitted issue from page: [/collect/show/](https://history.urn1350.net/collect/show/)
---
# 'Tell us about a show' form submission

Field | Data
----- | ----
Title | The Science Show
Date Start |  /  / 
Date End |  /  / 
Type | ???
Venue | Portland A Floor 

## Synopsis

Twitter - https://twitter.com/URNScienceShow
Previous podcasts - https://drive.google.com/drive/folders/0B9If_N6grH3ANHZoNzR6TV8yMFk

## Submitter

Field | Data
----- | ----
Name | Sam Osborne
Graduated | 2019

## Attempted File Generation

```
---
title: The Science Show
show_type: ??? (???)
show_type_sort: ??
period: ??
venue:
  - Portland A Floor 
date_start: --
date_end: --

cast:
  - role:
    name:

crew:
  - role: Director
    name:
  - role: Producer
    name:

comment: Details from Sam Osborne (2019)
published: true
---

Twitter - https://twitter.com/URNScienceShow
Previous podcasts - https://drive.google.com/drive/folders/0B9If_N6grH3ANHZoNzR6TV8yMFk
```
**
