### ISSUE TITLE
Nick Joe & Nick Show

### ISSUE THREAD

**Issue by urnbot** [URN/urn-history-project#8]
End user submitted issue from page: [/collect/show/](https://history.urn1350.net/collect/show/)
---
# 'Tell us about a show' form submission

Field | Data
----- | ----
Title | Nick Joe & Nick Show
Playwright | undefined
Date Start |  /  / 
Date End |  /  / 
Type | Daytime
Venue | Portland Basement

## Cast

Presenter - Nick Sutton-Smith
Presenter - Nick Clay
Presenter - Joe Tanner

## Submitter

Field | Data
----- | ----
Name | J
Graduated | 0

## Attempted File Generation

```
---
title: Nick Joe & Nick Show
playwright: undefined
show_type: ??? (Daytime)
show_type_sort: ??
period: ??
venue:
  - Portland Basement
date_start: --
date_end: --

cast:
  - role:
    name:

crew:
  - role: Director
    name:
  - role: Producer
    name:

comment: Details from J (0)
published: true
---


```
**
