### ISSUE TITLE
The Matt and James Show

### ISSUE THREAD

**Issue by urnbot** [URN/urn-history-project#86]
End user submitted issue from page: [/collect/show/](https://history.urn1350.net/collect/show/)
---
# 'Tell us about a show' form submission

Field | Data
----- | ----
Title | The Matt and James Show
Date Start | 31 / 10 / 2019
Date End |  /  / 
Type | Daytime
Venue | Portland C Floor

## Synopsis

Hasn't finished yet

## Presenters

Presenter - Matthew Webb
Presenter - James Aldred

## Submitter

Field | Data
----- | ----
Name | Matthew Webb
Graduated | 2020

## Attempted File Generation

```
---
title: The Matt and James Show
show_type: ??? (Daytime)
show_type_sort: ??
period: ??
venue:
  - Portland C Floor
date_start: 2019-10-31
date_end: --

cast:
  - role:
    name:

crew:
  - role: Director
    name:
  - role: Producer
    name:

comment: Details from Matthew Webb (2020)
published: true
---

Hasn't finished yet
```
**
