### ISSUE TITLE
The Official Pre Ocean Show

### ISSUE THREAD

**Issue by urnbot** [URN/urn-history-project#9]
End user submitted issue from page: [/collect/show/](https://history.urn1350.net/collect/show/)
---
# 'Tell us about a show' form submission

Field | Data
----- | ----
Title | The Official Pre Ocean Show
Playwright | undefined
Date Start |  /  / 
Date End |  /  / 
Type | After Dark
Venue | Portland Basement

## Cast

Presenter - Matt Manley

## Submitter

Field | Data
----- | ----
Name | J
Graduated | 0

## Attempted File Generation

```
---
title: The Official Pre Ocean Show
playwright: undefined
show_type: ??? (After Dark)
show_type_sort: ??
period: ??
venue:
  - Portland Basement
date_start: --
date_end: --

cast:
  - role:
    name:

crew:
  - role: Director
    name:
  - role: Producer
    name:

comment: Details from J (0)
published: true
---


```
**
